version: '3.4'

services:
  nosql-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27018:27017"
    volumes:
      - mongodb_test_data:/data/db
      - mongodb_test_config:/data/configdb

volumes:
  mongodb_test_data:
  mongodb_test_config: