version: '3.4'

services:
  nosql-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mono-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://admin:pass@nosql-db:27017
      - MongoDb__DatabaseName=MonoApp
    ports:
      - "1234:80"

volumes:
  mongodb_data:
  mongodb_config:
