version: '3.4'

services:
  nosql-db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    
  mono-api:
    image: ${REGISTRY:-keeper}/mono-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Mono.API/Dockerfile
    depends_on:
      - nosql-db
