version: '3.4'

services:
  web-spa:
    ports:
      - 4200:4200
    volumes:
      - ./web-spa:/project
      - node_modules:/project/node_modules
    networks:
      - mono-net
    
  mono-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1234:80"
    networks:
      - mono-net

volumes:
  node_modules:
    driver: local

networks:
  mono-net:
    driver: bridge
