version: '3.4'

services:
  nosql-db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: nosql-db
    
  reporting-api-unit-test:
    image: ${REGISTRY:-keeper}/reporting-api-unit-test:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Reporting/Reporting.API/Dockerfile
      target: unittest
      
  reporting-api-integration-test:
    image: ${REGISTRY:-keeper}/reporting-api-integration-test:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Reporting/Reporting.API/Dockerfile
      target: integrationtest
    depends_on:
      - nosql-db

  configuring-api-unit-test:
    image: ${REGISTRY:-keeper}/configuring-api-unit-test:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Configuring/Configuring.API/Dockerfile
      target: unittest
