version: '3.4'

services:
  web-spa:
    ports:
      - 4200:4200
    volumes:
      - ./MonoAPI/web-spa:/project
      - keeper-webspa-node-modules:/project/node_modules
    networks:
      - mono-net
    
  mono-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1234:80"
    networks:
      - mono-net

volumes:
  keeper-webspa-node-modules:
    driver: local

networks:
  mono-net:
    driver: bridge
