name: reporting-api

on:
  push:
    branches: [ "main" ]
    paths:
    - src/Services/Reporting/**
    - .github/workflows/reporting-api.yml
    - src/docker-compose-test.*.yml
  
  pull_request:
    branches: [ "main" ]
    paths:
    - src/Services/Reporting/**
    - .github/workflows/reporting-api.yml

jobs:
  unit_test:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: ./.github/workflows/composite/test
      with:
        service: reporting-api-unit-test
  
  integration_test:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: ./.github/workflows/composite/test
      with:
        service: reporting-api-integration-test
